### ISSUE TITLE
New Component: Video player

### ISSUE THREAD

**Issue by joshtynjala** [joshtynjala/feathers#1008]
Will be nice once [VideoTexture](http://blogs.adobe.com/flashplayer/2014/10/beta-feature-videotexture-and-stage3d.html) becomes available across multiple platforms.

May be split among multiple components. Seek bar with buffering, full screen button, play-pause button, etc.

**Comment by pol2095** [comment]
I have this Error: Call to a possibly undefined method attachNetstream through a reference with static type VideoTexture.
texture.attachNetstream(ns);

Thanks

**Comment by pol2095** [comment]
Is the Feathers VideoPlayer component manages pseudo-streaming like this Spark VideoPlayer plugin https://github.com/mexxik/osmf-pseudostreaming

**Comment by joshtynjala** [comment]
I'm afraid that I don't know what pseudo-streaming is. It simply passes a URL to the play() function of a NetStream object and uses Starling's Texture.fromNetStream() to create a VideoTexture. Nothing fancy.

**Comment by pol2095** [comment]
I installed the H264 Streaming Module on a centOS server, how I synchronize the SeekSlider width the URL to the play() ? Thanks

**Comment by joshtynjala** [comment]
You shouldn't need to do anything. Just add it as a child of the VideoPlayer. The SeekSlider will automatically determine its own maximum and value properties from the VideoPlayer's totalTime and currentTime properties. When you interact with the SeekSlider, it will automatically call seek() on the VideoPlayer as needed.
