### ISSUE TITLE
MetalWorksDesktopThemeWithAssetManager - texture size problem

### ISSUE THREAD

**Issue by b005t3r** [joshtynjala/feathers#1068]
I get the following error:

[Fault] exception, information=ArgumentError: The sum of the x and width properties of the scale9Grid must be less than or equal to the width of the texture.

thrown from here:

```as3
if((scale9Grid.x + scale9Grid.width) > textureFrame.width)
{
	throw new ArgumentError(SUM_X_REGIONS_ERROR);
}
```

scale9Grid.x == 5, scale9Grid.width == 1, textureFrame.width == 5.5

**Comment by joshtynjala** [comment]
Thank you. I can reproduce this issue.

**Comment by b005t3r** [comment]
I'm pretty sure that for this particular theme to work and look good scaleFactor has to be 1, regardless of windows size, so I think it could throw an exception when it's greater than 1 with an appropriate message.

**Comment by sebastianerb** [comment]
Is it possible, that this issue is actual again?
http://forum.starling-framework.org/topic/bug-texture-size-problem-argumenterror-in-scale9textures#post-88491
