### ISSUE TITLE
Button: Add resize listener for icon

### ISSUE THREAD

**Issue by alex-jaydee** [joshtynjala/feathers#1069]
Hey Josh,

For some reason the Button component doesn't listen for resize events from the icon in case when icon is a FeathersComponent. The workaround is to extend the button and add the listener manually, but there is another problem - in order to force the layout of the button you need to invalidate INVALIDATION_FLAG_STYLES, INVALIDATION_FLAG_STATE or any other important flag which will trigger the layout. And this is not good either. I see that you already checking if the icon is a FeathersComponent in refreshIcon method of the Button component, so why not to add a resize listener there? Considering that most of the buttons have just the images as the icons, this minor addition should not have a great impact on performance but might be very useful for complex scenarios.

Looking forward for your comments.
Thank you.

**Comment by joshtynjala** [comment]
I haven't needed it, and you're the first person to ask for it. It just hasn't come up before. It's a good idea, though. Thanks.
