### ISSUE TITLE
WaterfallLayout: implement IVirtualLayout interface

### ISSUE THREAD

**Issue by joshtynjala** [joshtynjala/feathers#1092]

**Comment by manofspirit** [comment]
Hi josh, is this layout can help solve the mentioned problem?
https://github.com/joshtynjala/feathers/issues/1077

**Comment by joshtynjala** [comment]
No, it's a completely different layout. WaterfallLayout is inspired by Pinterest's layout.

If I have time, I'll try to add a FlowLayout (#55) that could solve your issue. You'd need to manually set the widths of the items, but they'd be in rows that would have different heights.

**Comment by manofspirit** [comment]
Flow Layout is much better option :) please spare some time for it, Thanks
