### ISSUE TITLE
Names are not set for child components of Slider

### ISSUE THREAD

**Issue by b005t3r** [joshtynjala/feathers#1094]
This makes it impossible to do this for example:
```as3
var thumb:Button = slider.getChildByName(Slider.DEFAULT_CHILD_NAME_THUMB) as Button;
```

**Comment by b005t3r** [comment]
OK, just realized this is not supposed to be used like that. But is there any way of accessing Slider's child components then? What do I do when I want to e.g. display something on Slider's thumb (like current value)?

**Comment by joshtynjala** [comment]
Feathers no longer uses the name and nameList properties. In 2.0, I switched that functionality over to new styleName and styleNameList properties to clear up some conflicts. nameList still exists, but it became an alias for styleNameList, and it is deprecated for removal. Similarly, Slider.DEFAULT_CHILD_NAME_THUMB also still exists, but it's only temporary.

You can now set the thumb's name property yourself in the thumbFactory:

	slider.thumbFactory = function():Button
	{
		var thumb:Button = new Button();
		thumb.name = "thumb";
		return thumb;
	}

Then you are free to use getChildByName() with your custom name.

	slider.getChildByName("thumb");
