### ISSUE TITLE
ScrollContainer.as (getRawChildIndex method)

### ISSUE THREAD

**Issue by gabrielPeart** [joshtynjala/feathers#1099]
Hi Josh, first of all, congratulations for doing a very good job and thanks for giving us a very solid and robust framework. I do appreciate.

I was analysing the latest version of Feathers and found this block of code:

public function getRawChildIndex(child:DisplayObject):int
{
	var oldBypass:Boolean = this.displayListBypassEnabled;
	this.displayListBypassEnabled = false;
	return super.getChildIndex(child);
	this.displayListBypassEnabled = oldBypass;
}

The line: this.displayListBypassEnabled = oldBypass; will not be executed since we have the return super.getChildIndex(child); before.

I don't know if it's part of your new implementation:

this.displayListBypassEnabled = false;

and you just forgot to clean up the code.

**Comment by joshtynjala** [comment]
Thank you! I wish we had a better ActionScript compiler that would catch these sorts of issues.

**Comment by gabrielPeart** [comment]
You are welcome! Glad to know that was possible to help and contribute somehow.
Yes, I wish the same, but for now, we can go and help each other!
