### ISSUE TITLE
Font rendering bug on a 4K display on Windows

### ISSUE THREAD

**Issue by b005t3r** [joshtynjala/feathers#1102]
When running the demo for this project: https://github.com/b005t3r/TirePhysicsDemo on a 4K display on Windows, fonts are blurred (almost unreadable):

![screen](https://cloud.githubusercontent.com/assets/757150/6672691/5a089632-cc0e-11e4-90db-539b7ef3fa41.jpg)

**Comment by joshtynjala** [comment]
Everything appears to be scaled for some reason. You can see how the bitmap fonts looks distorted.

**Comment by b005t3r** [comment]
Yes, scaled, but like multiplied by an integer, so it's blurry. I suspect it has something to do wtih the DPI the theme uses, because other elements, like the one draw with Starling-Graphics extension are rendered correctly.

**Comment by joshtynjala** [comment]
MinimalDesktopTheme doesn't use DPI to scale. It actually doesn't scale the assets at all. It has a scale member variable, but only to allow subclasses to override the behavior. The default behavior simply sets it to 1.

**Comment by joshtynjala** [comment]
Which Context3DProfile is being used? Have you tried a different one?

**Comment by b005t3r** [comment]
Ah, didn't see your question. It was probably the standard one. Do you think that it matters?

**Comment by joshtynjala** [comment]
It might be worth trying several different profiles to see if any make a difference. My gut feeling says that this probably isn't a Feathers or Starling issue. Seems like more of a Stage 3D, GPU, or driver issue.

Unfortunately, I don't have a 4K display to test. The Retina display on my Mac laptop is the closest I have, but there's no blurring here.

**Comment by b005t3r** [comment]
This bug was happening on my friend's PC, so I can't try to reproduce it right now. I also think this has something to do with Stage3D or system settings, because my friend had a couple of settings altered, so fonts would render larger (Windows render tiny fonts on 4K displays by default as far as I know) and this probably had an impact on how Stage3D handles fonts as well. I don't know if there are any Stage3D specific methods/functions I could try to call to override the system defaults.

Anyway, if I'm the only one who had this issue, it's probably not worth looking into right now.

**Comment by joshtynjala** [comment]
That text is rendered with bitmap fonts, so we're seeing quads with textures. That wouldn't be affected by system font settings.

I wonder if the browser zoom settings could cause it. I just tried in Chrome on my Mac, and zooming in simply scaled what Flash Player was rendering, causing it to become blurry. It didn't look exactly like your screenshot, though. Just basic blurring without the odd distortion.
