### ISSUE TITLE
HorizontalLayout and verticalAlign justify

### ISSUE THREAD

**Issue by SamYStudiO** [joshtynjala/feathers#1103]
Hi Josh,

Seems i got a wrong sizing when i use horizontal layout with vertical justify and first item height is smaller than the next one. Looks like first item is used to compute global height instead of getting the heighest item.
Shouldn't be the highest item used to compute group size?

Thx

**Comment by joshtynjala** [comment]
Are you using a List? If so, then when useVirtualLayout is true, the typicalItem is used to calculate the group size. If you don't provide a custom typicalItem, then the first item in the data provider is used.

**Comment by SamYStudiO** [comment]
Nop i'm not using a List.
I got a LayoutGroup (horizontal layout vertical align justify) with 2 Radio, the 2 Radio have the same padding on each side, the first radio looks good but the second one padding top is too small, maybe a image would be better :
![screenshot](https://cloud.githubusercontent.com/assets/3678076/6713048/4ea1436a-cd90-11e4-92c2-126ed65f1442.png)

**Comment by SamYStudiO** [comment]
I tried to put the heighest one on the first position but still got the pb, does'nt seem its related to the first added child

**Comment by SamYStudiO** [comment]
Also forgot to tell i use a layout data percentWidth 50 on each Radio

**Comment by joshtynjala** [comment]
Thank you! I was able to reproduce the issue. The Button class (which is the superclass of Radio) didn't set an appropriate maxHeight on its label text renderer that accounted for the Radio's height and its padding. That has been fixed.

**Comment by SamYStudiO** [comment]
Great thx for the fix!

**Comment by SamYStudiO** [comment]
Hey Josh,

coming back for this since i still got the pb with current git version (just downloaded it). In addition as you may see with screenshot vertical align justify isn't working with nested layout group (last text is not wordwraped)
here the code i use inside a screen initialization :

```actionscript
var screenLayout : VerticalLayout = new VerticalLayout();
screenLayout.horizontalAlign = VerticalLayout.HORIZONTAL_ALIGN_JUSTIFY;
layout = screenLayout;

var radioGroup : LayoutGroup = new LayoutGroup();
addChild( radioGroup );

var radioLayout : HorizontalLayout = new HorizontalLayout();
radioLayout.verticalAlign = HorizontalLayout.VERTICAL_ALIGN_JUSTIFY;

radioGroup.layout = radioLayout;

var ld : HorizontalLayoutData = new HorizontalLayoutData();
ld.percentWidth = 50;

var tf : TextFormat = new TextFormat();
tf.align = TextFormatAlign.CENTER;

var r1 : Radio = new Radio();
r1.label = "Lorem ipsum dolor sit amet";
r1.defaultIcon = new Quad( 50 , 50 , 0xff0000 );
r1.iconPosition = Button.ICON_POSITION_BOTTOM;
r1.padding = 50;
r1.layoutData = ld;
r1.defaultLabelProperties.wordWrap = true;
r1.defaultLabelProperties.textFormat = tf;
r1.horizontalAlign = Button.HORIZONTAL_ALIGN_CENTER;
r1.verticalAlign = Button.VERTICAL_ALIGN_BOTTOM;
radioGroup.addChild( r1 );

var r2 : Radio = new Radio();
r2.label = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lorem mauris, ornare quis magna tristique, condimentum varius lorem.";
r2.defaultIcon = new Quad( 50 , 50 , 0xff0000 );
r2.iconPosition = Button.ICON_POSITION_BOTTOM;
r2.padding = 50;
r2.layoutData = ld;
r2.defaultLabelProperties.wordWrap = true;
r2.defaultLabelProperties.textFormat = tf;
r2.horizontalAlign = Button.HORIZONTAL_ALIGN_CENTER;
r2.verticalAlign = Button.VERTICAL_ALIGN_BOTTOM;
radioGroup.addChild( r2 );

var label : Label = new Label();
label.textRendererProperties.wordWrap = true;
label.padding = 50;
label.text = "OK Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lorem mauris, ornare quis magna tristique, condimentum varius lorem. Curabitur nunc felis, luctus in nibh viverra, congue semper ipsum. Phasellus ullamcorper orci vel ornare auctor. Vestibulum non neque odio. Morbi non libero tincidunt, pretium elit ut, aliquet ipsum. Donec sit amet lacinia est. Sed nec posuere sapien. Nunc et diam dolor. Vivamus in nibh nec justo dictum dapibus dapibus mollis lacus. Donec convallis est vitae arcu iaculis, sed porttitor sem luctus. Nam iaculis blandit ante ut sodales. Maecenas neque mauris, egestas id convallis non, bibendum vitae erat. Nulla nisl lacus, rutrum id lacus at, sollicitudin dignissim mauris. Sed eget auctor erat. Fusce iaculis arcu vel odio cursus commodo.";
addChild( label );

var footerGroup : LayoutGroup = new LayoutGroup();
var footerLayout : VerticalLayout = new VerticalLayout();
footerLayout.padding = 50;
footerGroup.layout = footerLayout;

label = new Label();
label.textRendererProperties.wordWrap = true;
label.text = "KO Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lorem mauris, ornare quis magna tristique, condimentum varius lorem. Curabitur nunc felis, luctus in nibh viverra, congue semper ipsum. Phasellus ullamcorper orci vel ornare auctor. Vestibulum non neque odio. Morbi non libero tincidunt, pretium elit ut, aliquet ipsum. Donec sit amet lacinia est. Sed nec posuere sapien. Nunc et diam dolor. Vivamus in nibh nec justo dictum dapibus dapibus mollis lacus. Donec convallis est vitae arcu iaculis, sed porttitor sem luctus. Nam iaculis blandit ante ut sodales. Maecenas neque mauris, egestas id convallis non, bibendum vitae erat. Nulla nisl lacus, rutrum id lacus at, sollicitudin dignissim mauris. Sed eget auctor erat. Fusce iaculis arcu vel odio cursus commodo.";
footerGroup.addChild( label );

addChild( footerGroup );
```

![shot](https://cloud.githubusercontent.com/assets/3678076/6831087/7444be60-d31e-11e4-8e5d-d55f1e52997c.png)

**Comment by joshtynjala** [comment]
It won't wrap if the Label doesn't have an explicit or maximum width. If you want all children to fill the full width of the `footerGroup`:

	footerLayout.horizontalAlign = VerticalLayout.HORIZONTAL_ALIGN_JUSTIFY;

Or you can use VerticalLayoutData with percentWidth set to 100 on individual children:

	label.layoutData = new VerticalLayoutData(100);

On an unrelated note, I recommend using the new wordWrap property on Label. No need to set it through textRendererProperties anymore.

	label.wordWrap = true;

**Comment by SamYStudiO** [comment]
Indeed make sense to also apply justify to sub group, dunno why i didn't think about that!
Any idea why the second radio size is incorrect? It's look height is compute with single line, i guess for now i may validate radio manually to set correct height.

Thx!

**Comment by joshtynjala** [comment]
I fixed the issue with the height of the radios. There was a bug in HorizontalLayout when using percentWidth where the height wasn't always calculated correctly.

**Comment by SamYStudiO** [comment]
It works! Thx you!
