### ISSUE TITLE
Different appearance (wrong font size) of TextInput (TextFieldTextEditor) for iPad Retina and iPhone3

### ISSUE THREAD

**Issue by Mintonist** [joshtynjala/feathers#1104]
![f7b822ae8f7761f0a95f902e60a6d2cd](https://cloud.githubusercontent.com/assets/9267850/6753045/409b28d6-cf24-11e4-8dde-1c53e5337556.png)
![fdc63825253bdc6c65f567361fa2029e](https://cloud.githubusercontent.com/assets/9267850/6753044/4096e974-cf24-11e4-9d2f-26e574e1c3ce.png)

Code for this textfield:
/////////////////////////////////
		////// INPUT TEXT ///////////////
		_input = new TextInput();

                 // we use x,y,w,h from other screen object and replace them with feather TextInput
		_input.x = _mcWindow.t_input.x;
		_input.y = _mcWindow.t_input.y;
		_input.width = _mcWindow.t_input.width;
		_input.height = _mcWindow.t_input.height;
		_input.text = "";
		_mcWindow.removeChild(_mcWindow.t_input);
		_mcWindow.addChild(_input);

		_input.maxChars = 128;

		_input.textEditorFactory = function():ITextEditor
		{
			var editor:TextFieldTextEditor = new TextFieldTextEditor();
			editor.isEditable = true;
			editor.multiline = false;
			editor.textFormat = new TextFormat("Obelixttf", 16, 0x808080, true);
			editor.textFormat.align = TextFormatAlign.LEFT;

			return editor;
		}

And I set Starling for all screens this way:

		var fullScreenWidth:int = stage.fullScreenWidth;
		var fullScreenHeight:int = stage.fullScreenHeight;

		stage.scaleMode = StageScaleMode.NO_SCALE;
		stage.align = StageAlign.TOP;
		stage.frameRate = 20;

		Starling.multitouchEnabled = true;  // useful on mobile devices
		Starling.handleLostContext = true;//!iOS;  // not necessary on iOS. Saves a lot of memory!

		// launch Starling
		var viewPort:Rectangle = new Rectangle(0, 0, fullScreenWidth, fullScreenHeight);     

		var logicalScreenHeight:Number = 640;
		var stageSizeCoeff:Number = logicalScreenHeight/fullScreenHeight;

		mStarling = new Starling(Game, stage, viewPort, null, "auto", "auto");
		
		mStarling.stage.stageWidth  = fullScreenWidth*stageSizeCoeff;
		mStarling.stage.stageHeight = fullScreenHeight*stageSizeCoeff;

What is wrong? Why we see so diferent font sizes?

Thx!

**Comment by joshtynjala** [comment]
Thank you. I can reproduce this issue.

**Comment by Mintonist** [comment]
I am not shore but seems it is connected with that we use embeded font

[Embed(source="../fonts/ObelixPro.ttf", embedAsCFF="false", fontFamily="Obelixttf", fontWeight="bold")]
private static const ObelixProBold:Class;

Font link if needed - https://www.dropbox.com/s/9kjle2xw673432w/ObelixPro.ttf?dl=0

But real font (which displayed) was not Obelixttf. I dont know how it works
