### ISSUE TITLE
Scroller.clipContent bag where interactionMode=INTERACTION_MODE_MOUSE

### ISSUE THREAD

**Issue by alevys** [joshtynjala/feathers#1105]
Hi! If you scroll on INTERACTION_MODE_MOUSE clipContent is calculated incorrectly.

**Comment by joshtynjala** [comment]
I cannot reproduce this issue.

Please provide some code that will reproduce the issue. It would help me a lot if you could simplify the code down to the bare minimum that is needed to demonstrate the issue. Try not to send a whole project. Just something that's easy for me to copy and paste into my editor and run it without many tweaks.

**Comment by alevys** [comment]
public class ScrollerBug extends ScrollContainer
	{
		private var _lastQuad:Quad;

		public function ScrollerBug() {
			super();
		}

		override protected function initialize():void {
			addAllQuad();

			var layout:VerticalLayout = new VerticalLayout();
			layout.horizontalAlign = VerticalLayout.HORIZONTAL_ALIGN_JUSTIFY;
			layout.gap = 2;
			this.layout = layout;

			horizontalScrollPolicy = SCROLL_POLICY_OFF;
			scrollBarDisplayMode = SCROLL_BAR_DISPLAY_MODE_FIXED;
			interactionMode = INTERACTION_MODE_MOUSE;
			verticalScrollStep = 1;
			verticalMouseWheelScrollStep = 10;

			height = 430;
			width = 220;
		}

		private function addAllQuad():void {
			for (var i:int = 0; i < 11; i++) {
				var quad:Quad = new Quad(220, 40, Color.GREEN);
				addChild(quad);
			}

			_lastQuad = new Quad(220, 40, Color.RED);
			_lastQuad.addEventListener(TouchEvent.TOUCH, handler_touch);
			addChild(_lastQuad);
		}

		private function handler_touch(event:TouchEvent):void {
			var touch:Touch = event.getTouch(_lastQuad, TouchPhase.ENDED);
			if (touch) {
				removeChildAt(0);
				removeChildAt(0);
				removeChildAt(0);
			}
		}
	}

Scroll down and press the red button. 
If interactionMode = INTERACTION_MODE_MOUSE there is an error.

**Comment by joshtynjala** [comment]
Thank you! That was exactly what I needed to find the issue.
