### ISSUE TITLE
TextBlockTextRenderer: wrong size after restoring lost context

### ISSUE THREAD

**Issue by rozd** [joshtynjala/feathers#1106]
Hi!
I noticed that `TextBlockTextRenderer` displays text incorrectly during restoring lost context. The new size is about twice as little than before.

This is application after launch, before context lost:

![img_0469](https://cloud.githubusercontent.com/assets/158493/6754382/de216b42-cf24-11e4-98b5-40b31e5974ed.PNG)

and this is after context restored:

![img_0470](https://cloud.githubusercontent.com/assets/158493/6754383/de22e3aa-cf24-11e4-8e50-a2766116a1bd.PNG)

I use `CameraRoll.browseForImage()` to cause context lost:

```as3
label = new Label();
label.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";
label.wordWrap = true;
addChild(label);

button = new Button();
button.label = "Camera";
button.addEventListener(Event.TRIGGERED, function(event:Event):void
{
    if (CameraRoll.supportsBrowseForImage)
    {
        var camera:CameraRoll = new CameraRoll();

        camera.browseForImage();
    }
});
addChild(button);

invalidate(INVALIDATION_FLAG_LAYOUT);
```

Thanks!

**Comment by joshtynjala** [comment]
Any chance that this happens when contentScaleFactor is not equal to 1? I am able to produce a runtime error when contentScaleFactor is 2.
