### ISSUE TITLE
Wrong font size on second monitor

### ISSUE THREAD

**Issue by kavolorn** [joshtynjala/feathers#1107]
Hi Josh,

I'm using current Feathers (20th March commits) and playing with supportHighResolutions option for Starling. It is working as expected on my macbook retina screen. But when I drag window to the second monitor I have problems with fonts. I've prepared screens from 2 monitors:

![screen shot 2015-03-22 at 11 23 50](https://cloud.githubusercontent.com/assets/2448274/6768764/5a112cca-d087-11e4-8c79-32cfc676fdd9.png)
![screen shot 2015-03-22 at 11 23 56](https://cloud.githubusercontent.com/assets/2448274/6768765/5a116956-d087-11e4-898b-d34361aa1234.png)

Some problem with texture size I think. It looks 2 times smaller. Do you know what is wrong?

Thanks

**Comment by joshtynjala** [comment]
Is that a TextInput? If so, which text editor are you using?

**Comment by kavolorn** [comment]
This is the code for input field:

```actionscript3
var text:TextInput = new TextInput();
text.text = "Sample text";
text.width = stage.stageWidth;
text.height = 200;
addChild(text);
```

And this is how styles are defined in custom theme:

```actionscript3
private function initializeGlobals():void
{
	FeathersControl.defaultTextEditorFactory = function():ITextEditor {
		return new TextBlockTextEditor();
	}
	FeathersControl.defaultTextRendererFactory = function():ITextRenderer {
		return new TextBlockTextRenderer();
	}
}
private function setTextInputStyle(textInput:TextInput):void
{
	var fontDescription:FontDescription = new FontDescription("RobotoRegular", FontWeight.NORMAL, FontPosture.NORMAL, FontLookup.EMBEDDED_CFF, RenderingMode.CFF, CFFHinting.NONE);
	var elementFormat:ElementFormat = new ElementFormat(fontDescription, 12, Color.BLACK);
	textInput.textEditorProperties.elementFormat = elementFormat;
	
	textInput.backgroundSkin = new Quad(2, 2, Color.AQUA);
}
```

So this is TextBlockTextEditor. For TextFieldTextEditor same thing when field is not selected. Same texture problem exists for Label component with TextBlockTextRenderer.
