### ISSUE TITLE
List + CustomItemRenderer + Cube Transition = can't change selectedItem on list;

### ISSUE THREAD

**Issue by N0N4M3pl** [joshtynjala/feathers#1115]
# Working code:
I created list with custom item renderer - like in cookbook from help.
To customItemRenderer i added all code for changing selection on list.
In mediator (for view where is added list as child) i added listener for CHANGE event - to watch selectedItem in list.
So after clicking on element on list, event was dispatched and handler in mediator was executed.
**ScreenNavigator use ScreenSlidingStackTransitionManager.**
**Feathers version: 2.0.1**

# NOT working code:
I have updated to new version of **Feathers 2.1.1**.
Then i have changed ScreenNavigator.transition into **Cube.createCubeUpTransition**.
Selecting item stops working.

Changing ScreenNavigator.transition into ColorFade.createBlackFadeToBlackTransition helps.

**Comment by joshtynjala** [comment]
When you say that it "stops working", what do you mean? Please be specific. Thank you!

**Comment by N0N4M3pl** [comment]
### *Selecting item stops working.* mean:
ItemRenderer has code:
```actionscript
override protected function initialize():void {
        if (!_label) {
            _label = new Label();
            addChild(_label);

            addEventListener(TouchEvent.TOUCH, onTouch);
            addEventListener(Event.REMOVED_FROM_STAGE, onRemovedFromStage);
        }
    }
```
onTouch handler is never execute when ScreenNavigator.transition is set by Cube.createCubeUpTransition() function.

I think Cube transitions blocks dispatching events in ItemRenderes on List.

**Comment by joshtynjala** [comment]
Perhaps a runtime error is happening somewhere. Have you tried running in the debugger?

One thing worth noting is that Cube and other 3D transitions need to remove the screen from its parent and then add it to a Sprite3D. This could cause issues in certain situations. For instance, if you have a listener for Event.ADDED_TO_STAGE, and you don't expect it to be called more than once, you may be getting an error.

**Comment by N0N4M3pl** [comment]
Thanks for help.

This helped: *Cube and other 3D transitions need to remove the screen from its parent and then add it to a Sprite3D*

After showing screen (using Cube translation) listener for touch is removed.
My code for remove from stage was:
```actionscript
protected function onRemovedFromStage(event:Event):void {
        removeEventListener(TouchEvent.TOUCH, onTouch);
        removeEventListener(Event.REMOVED_FROM_STAGE, onRemovedFromStage);

        _touchPointId = -1;
}
```

So it was my code - i didn't checek how works 3D translation.
Maybe You can add some info in documatation or help about this.

Thanks for help
