### ISSUE TITLE
Spinner list like iOS

### ISSUE THREAD

**Issue by SamYStudiO** [joshtynjala/feathers#1117]
Hello Josh,

I'm trying to reproduce iOS spinner when you may snap to each row and auto select row in the middle of the list.
Have you implemented such a possibility yet? At least the possibilities to snap to each row?

Thx!

**Comment by joshtynjala** [comment]
Like this? http://feathersui.com/help/spinner-list.html

**Comment by SamYStudiO** [comment]
Oh yes i missed it! I was trying to use List with VerticalSpinnerLayout :)

Thx Josh!
