### ISSUE TITLE
ProgressBar MetalWorksTheme value display bug

### ISSUE THREAD

**Issue by SirGordon** [joshtynjala/feathers#1121]
Instantiate a theme with scale to dpi = false.
Add a progress bar to the stage, make it small, for example 48x4.
Set minimum to 0 and maximum to 100.
Now set value to different numbers.
For example, value=10 may look like 50.

**Comment by joshtynjala** [comment]
MetalWorksMobileTheme or MetalWorksDesktopTheme?

The minimum width of the progress bar fill in MetalWorksMobileTheme is 22 pixels. Below that size, the skin starts to distort, and it looks terrible. This is the expected behavior.

**Comment by SirGordon** [comment]
Thank you for a quick response. I'm using ProgressBar as a health bar of a unit in a game, so it has to be that small.

**Comment by joshtynjala** [comment]
In that case, you should create a skin that can scale to a smaller width.

**Comment by SirGordon** [comment]
On devices, I'm setting scale to dpi = true, so it works well. But on PC, when setting it to true, text and controls look too little, so i set scale to dpi = false.
