### ISSUE TITLE
TextFieldTextEditor: this.textField.antiAliasType = AntiAliasType.ADVANCED; 

### ISSUE THREAD

**Issue by gAnS3** [joshtynjala/feathers#1124]
I notice than using TextFieldTextEditor embed fonts get blurry. Adding AntiAlias avoid this issue. For some reason you dont add this property?. Thanks for your work, its great

**Comment by gAnS3** [comment]
Okk, thanks 
you're quick as a flash

**Comment by joshtynjala** [comment]
I haven't made any changes...

**Comment by gAnS3** [comment]
Your quick response ..
