### ISSUE TITLE
add *.properties to .gitingnore

### ISSUE THREAD

**Issue by actionsmile** [joshtynjala/feathers#1130]
Add *.properties and build files to .gitignore, please. Instead you can provide template for this files. For instance, I use next technique:
`build.properties.template` — this file contains all my local values for SDK, players and so on. All you need is to copy this files as `build.properties`, which excluded by git in `.gitignore` file. It helps my team to avoid conflicts when they pulling or pushing updates.
Now, I forked you repo and changed all variables to match my local system, then build it to get `swc`-file and when you pushed updates I get a conflict each time :)

Thank you.

**Comment by joshtynjala** [comment]
You can create files named `build.local.properties` and `sdk.local.properties` to define your local paths. These files will be loaded first by `build.xml`, so any properties that they define will take precedence. You don't need to redefine every property either. For instance, you might set `airsdk.root` in `sdk.local.properties` and then `sdk.properties` will use your value to set any properties like `airsdk.bin` and `airsdk.lib`. These two `.local.properties` files are excluded with .gitignore.

**Comment by actionsmile** [comment]
Thanks, I saw that opportunity with a little help from my friend, which pointed me and closed ticket… sorry for not paying attention on that first.
