### ISSUE TITLE
filter with cache has problem in scroller

### ISSUE THREAD

**Issue by hejiacong** [joshtynjala/feathers#1135]
the test code
```javascript
	private function filterCacheInScroller():void
	{
		var container:ScrollContainer = new ScrollContainer();
		container.hasElasticEdges=false;
		container.interactionMode=Scroller.INTERACTION_MODE_TOUCH;
		container.horizontalScrollPolicy=Scroller.SCROLL_POLICY_OFF;
		container.verticalScrollPolicy=Scroller.SCROLL_POLICY_ON;
		container.setSize(400,400);
		for (var i:int = 0; i < 20; i++) 
		{
			var filterQuad:Quad=new Quad(300,50,Color.BLACK);
			filterQuad.x=50;
			filterQuad.y=50+100*i;
			var filter:FragmentFilter=BlurFilter.createGlow(Color.BLUE,1,4);
			filter.cache();
			filterQuad.filter=filter;
			container.addChild(filterQuad);
		}
		
		this.addChild(container);
	}
```

the Quad outside Scroller have no filter effect,the reason is filter.cache().
use filter.cache() is for performance,is there any good solution?

**Comment by joshtynjala** [comment]
Scroller uses Starling's clipRect, which seems to have issues with filters sometimes. There's nothing that I can do in Feathers to fix it, as far as I know. It seems to be a Starling issue.

I suspect that your issue may be related to Gamua/Starling-Framework#711 and/or Gamua/Starling-Framework#717. I think Daniel has committed some fixes recently that may help you.
