### ISSUE TITLE
Access to Flash (Start.as) from Starling/Feathers

### ISSUE THREAD

**Issue by svonnidmeg** [joshtynjala/feathers#1136]
Hi Josh,

I saw the posts about nativeStage in Starling, but don't know if is really what I need in my case. Let me explain what want to do:

In your examples the first class is Start.as (usually Flash AS3 class) and create the Starling... OK

Then there are a function called when the Starling is created (starling_rootCreatedHandler) with the next listener:

this._starling.addEventListener("rootCreated", starling_rootCreatedHandler);

Ok. Then into the listener function the launchImage is removed with a fade out:

this.removeChild(this._launchImage);
this._launchImage.unloadAndStop(true);
this._launchImage = null;

WHAT I WANT TO DO IS THE NEXT:

I need to call the starling_rootCreatedHandler function from the MainMenuScreen (the first Screen showed in your examples) with it own FeathersEventType.TRANSITION_IN_COMPLETE in order to remove the launchImage when the 1st Screen in Feathers ended the transition in.

Want to remove the Starling "rootCreated" listener and decide when I want to remove the launchImage.

Understand me? Make sense 4U?

Thx!

**Comment by joshtynjala** [comment]
I have responded to your forum thread.
