### ISSUE TITLE
Incorrectly calculated text crop in TextInput where switch to fullScreen.

### ISSUE THREAD

**Issue by alevys** [joshtynjala/feathers#1140]
Hi! Incorrectly calculated text crop in TextInput where switch to fullScreen.

**Comment by joshtynjala** [comment]
Could it be that the aspect ratio of the Starling stage and the Starling view port don't match up? Perhaps Starling is rendering somewhat distorted.

**Comment by joshtynjala** [comment]
Closing, since there was no response. I will investigate further if you can provide some code to reproduce the issue.
