### ISSUE TITLE
Anybody know if Adobe AIR will can publish for Apple Watch / Samsung Gear / whatever platforms too?

### ISSUE THREAD

**Issue by svonnidmeg** [joshtynjala/feathers#1146]
Hi Josh,

Do you know if Adobe or whatever are thinking in be able to publish with AIR/Starling/Feathers for this new gears?

Thx!

**Comment by joshtynjala** [comment]
The [Starling forums](http://forum.starling-framework.org/) is probably a better place to ask this.

I have not heard anything. If it's something that Adobe specifically needs to change the runtime to support, then I'd guess that they aren't planning anything unless watch platforms get super-popular.
