### ISSUE TITLE
Textinput component delay creation a lot!!

### ISSUE THREAD

**Issue by svonnidmeg** [joshtynjala/feathers#1150]
Hi Josh,

Updated latest feathers and noticed this:

I have an app with a screen that when is called by navigator (typical menu) generate a layoutGroup (as container) with a textinput into.

Well... When the screen is called a pause in all app appears. All rest freeze for 1-2 seconds then start the animation to change screen.

I tried to change all elements in screen called, but only works perfect if textinput component is not added.

I hope understanding what I mean (my English is poor, sorry)

**Comment by joshtynjala** [comment]
Did you also update Starling or AIR at the same time? Or did you update only Feathers?

When you say "latest", do you mean version 2.1.1 or the latest commit from Github?
