### ISSUE TITLE
SpinnerList returning wrong selectedItem

### ISSUE THREAD

**Issue by Pandan** [joshtynjala/feathers#1156]
Seems like the SpinnerList is returning wrong selectedItem.
When using snapToPages and listening to Event.CHANGE and then checking list.selectedItem . I can reproduce this with both Vertical and HorizontalSpinnerLayout. 
This seems to be a bug on the current master branch. Cause if I am switching back and using and older version(when only vertical layout existed) of feathers is actually working. 

I have also noticed that the Event.CHANGE is not always dispatched. Haven't found a pattern but seems like it sometimes happens if I am swipe:ing between two items that is next to each other.

**Comment by joshtynjala** [comment]
Thanks. I'll take a look!

**Comment by Pandan** [comment]
Where u able to reproduce this?

**Comment by joshtynjala** [comment]
I've been working hard on finishing the beta release of the Feathers SDK. I'll be able to look later this week.

**Comment by Pandan** [comment]
I understand, not meaning to stress you. :)
