### ISSUE TITLE
AutoComplete : Selection Bug when used in a Popup

### ISSUE THREAD

**Issue by manofspirit** [joshtynjala/feathers#1158]
Hi Josh,

I recently reported a bug which you fixed #1141 
Now there is a new bug, when i try to select an item from autocomplete, popup closes with autocomplete but that item stays there.

This doesnt happen when i use a pickerlist.

Please advise

**Comment by joshtynjala** [comment]
The item renderer is still visible after the pop-up closes?

**Comment by manofspirit** [comment]
I have a panel screen which i use as popup.
i have both autocomplete and picker in it. when i click picker, picker shows all item, and so autocomplete
however when i select an item autocomplete with popup closes but item stays there. but pickerlist works fine. which means something is wrong with autocomplete

**Comment by joshtynjala** [comment]
> but item stays there

I was trying to ask what this means. Can you be more specific. What item are you referring to? And where does it stay?

**Comment by manofspirit** [comment]
itemrenderer stays there, the item i selects
it looks like popup get the touch event first and closes it.

**Comment by joshtynjala** [comment]
Try passing a DropDownPopUpContentManager with its isModal property set to true to the popUpContentManager property of the AutoComplete.

**Comment by manofspirit** [comment]
yes, it works with that.
Thank you :)
