### ISSUE TITLE
Feathers SDK: Access of undefined property SplashScreen in IntelliJ IDEA

### ISSUE THREAD

**Issue by eRistocracy** [joshtynjala/feathers#1161]
I have followed all instructions from getting started with Feathers SDK in IntelliJ and pasted your sample code with a button and I get:

Error:[WieliczkaFLEX]: _WieliczkaFeathers_feathers_core_StarlingBootstrap.as: Error code: 1120: Access of undefined property SplashScreen.

and

Error:[WieliczkaFLEX]: _WieliczkaFeathers_feathers_core_StarlingBootstrap.as: Error code: 1172: Definition spark.preloaders:SplashScreen could not be found.

WieliczkaFLEX/WieliczkaFeathers are names of my app/module

**Comment by joshtynjala** [comment]
I just fixed that error in the included airmobile-config.xml, which Flash Builder uses, but I forgot that IntelliJ IDEA ignores the configuration files in the SDK and generates its own defaults. You'll want to clear the `-preloader` compiler argument. If I remember correctly, you can do that like this:

```
-preloader=
```

Just leave the right side blank.

**Comment by eRistocracy** [comment]
It worked, but only once :(
The button has appeared, but after second launch it showed:

Error:[WieliczkaFLEX]: java.net.SocketTimeoutException: Accept timed out
Error:[WieliczkaFLEX]: Unrecognized option: -debug=false
Could not create the Java virtual machine.

**Comment by joshtynjala** [comment]
I've never seen that error before. It seems like IntelliJ is having trouble talking to the JVM or something. Seems potentially unrelated to the Feathers SDK.

Have you accidentally added -debug=false to some command line arguments? Maybe to the launch options for ADL or something?

**Comment by joshtynjala** [comment]
Closing. Please move further discussion to BowlerHatLLC/feathers-sdk#6
