### ISSUE TITLE
Consider making *ScreenNavigatorItem.screen Bindable

### ISSUE THREAD

**Issue by teotigraphix** [joshtynjala/feathers#1167]
The issue is that using <fx:Class> does not refactor in InelliJ, so if you are creating a mildly large app, refactoring the name or package of the Screen class does not get updated in the MXML declaration.

Using;

```
private var fileBrowser:Class = FileBrowser;
```

```
<f:StackScreenNavigatorItem id="LibraryBrowser_FileBrowser" screen="{fileBrowser}">
```

Does work but I get compiler warnings, and usually I have no warnings. The warning is the "can't detect data binding"

So making `screen` Bindable should remove those warnings correct?

Thanks

**Comment by joshtynjala** [comment]
I don't think that making `screen` bindable will do the trick. That would allow you to do something like `someProperty="{LibraryBrowser_FileBrowser.screen}"` without any warnings, but a property doesn't need to be bindable for you to use curly brace {} syntax to pass a value to it.

With your workaround, if you make `fileBrowser` bindable, that should keep you from getting warnings.

``` as3
[Bindable]
private var fileBrowser:Class = FileBrowser;
```

Can you submit any futures issues related to MXML and binding to BowlerHatLLC/feathers-sdk instead? Technically, the code for the SDK's UI components lives in a special branch here, but I'd like to keep the issues separate, if possible. Thanks, Mike!

**Comment by teotigraphix** [comment]
Sorry for that, once I posted I was guessing maybe it was Feathers since it was in a feathers class.

I can't believe I didn't check Bindable on the prop, I am still rusty with MXML. :)
