### ISSUE TITLE
ImageLoader add a scaleMode property

### ISSUE THREAD

**Issue by SamYStudiO** [joshtynjala/feathers#405]
Actually scaleMode with images is always "SHOW_ALL", sometimes we need "NO_BORDER" so i guess externalize this as a property would be great

**Comment by rwolffgang** [comment]
I'm useing a clipped ImageLoader as a loading bar. After upgrading Feathers to the latest commit, the clipRect property gets overwritten, set to null. I traced the problem down to the commit that fixed this issue, but introduced the new behavior.

Around line ImageLoader.as:1611 in commit 8c959cb7beb8bcd2c746bb53757b2f1a137aee77 the property clipRect is set to null.

Simple example:
```actionscript
		protected function placeProgressBar():void
		{
			_progressBar = new ImageLoader(); 
			_progressBar.source = Texture.fromBitmap(new _progressBarTexture());
			
			var layoutData:AnchorLayoutData = new AnchorLayoutData();
			[...]
			_progressBar.layoutData = layoutData;
			
			_progressBar.clipRect = new Rectangle(0, 0, 0, 37);
		}

		private function onProgress(quickUpdate:Boolean = false):void
		{
			var progress:Number = _preloader.calculateProgress();

			// because the function _progressBar.layout is executed from 
			// somewhere else, the clipRect is null here
			if (quickUpdate)
				_progressBar.clipRect.width = _progressBar.width * progress;
			else
				TweenLite.to(_progressBar.clipRect, 0.5, {
					width: _progressBar.width * progress
				});
		}
```

Any new property, that I'm missing or is it a bug?

**Comment by joshtynjala** [comment]
If you set scaleContent to false, you can now change the width and height of the ImageLoader, and it will manage the clipRect for you. To get the original width and height of the texture, use the originalSourceWidth and originalSourceHeight properties.

**Comment by rwolffgang** [comment]
Thanks, now that makes sense. Because the width property changed, it messed with the horizontally centered layout, but that's nothing a little maths can't solve. :-)
